apiVersion: v1
kind: ReplicationController
metadata:
  name: faatisite
spec:
  replicas: 3
  selector:
    app: faatisite
  template:
    metadata:
      labels:
        app: faatisite
    spec:
      containers:
      - image: faati/yenidenmerhaba
        imagePullPolicy: IfNotPresent
        name: static-page-faati
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: faatisite
  labels:
    app: faatisite
spec:
  selector:
    app: faatisite
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
