apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world
spec:
  replicas: 5
  selector:
    name: hello-world-cont
  template:
    metadata:
      labels:
        name: hello-world-cont
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: hello-world-cont
