apiVersion: v1
kind: ReplicationController
metadata:
  name: faatisite
spec:
  replicas: 1
  selector:
    app: faatisite
  template:
    metadata:
      labels:
        app: faatisite
    spec:
      containers:
      - image: faati/yenidenmerhaba
        imagePullPolicy: IfNotPresent
        name: static-page-faati
        ports:
        - containerPort: 8080
