FROM python:3

ADD * /

RUN pip3 install bottle
RUN pip uninstall pip uninstall ndg-httpsclient
USER root

EXPOSE 8080

#ENTRYPOINT ["/usr/bin/python3", "./bottle_app.py"]

CMD [ "python" , "./bottle_app.py" ]
